apiVersion: v1
kind: Service
metadata:
  name: appointments
  labels:
    app: appointments
spec:
  selector:
    app: appointments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
