apiVersion: v1
kind: Service
metadata:
  name: crater-atomfeed           # ✅ Service name
  labels:
    app: crater-atomfeed          # ✅ Labels for identification
spec:
  type: ClusterIP                 # ✅ Default service type; internal access
  selector:
    app: crater-atomfeed          # ✅ Selects pods with this label
  ports:
    - name: http
      protocol: TCP
      port: 80                    # ✅ Port exposed inside the cluster
      targetPort: 8080            # ✅ Port your app listens to inside the pod
