# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: crater-php
#   labels:
#     app: crater-php
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: crater-php
#   template:
#     metadata:
#       labels:
#         app: crater-php
#     spec:
#       containers:
#         - name: crater-php
#           image: 779846789022.dkr.ecr.ap-south-1.amazonaws.com/crater-php:1.0.0
#           ports:
#             - containerPort: 9000
      # imagePullSecrets:
      #   - name: regcred

apiVersion: apps/v1
kind: Deployment
metadata:
  name: crater-php
  labels:
    app: crater-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crater-php
  template:
    metadata:
      labels:
        app: crater-php
    spec:
      containers:
        - name: crater-php
          image: 779846789022.dkr.ecr.ap-south-1.amazonaws.com/crater-php:1.0.0
          ports:
            - containerPort: 9000
          env:
            - name: CRATER_PHP_IMAGE_TAG
              value: "1.0.0"
            - name: CRATER_NGINX_IMAGE_TAG
              value: "1.0.0"
            - name: CRATER_APP_URL
              value: "https://payments-a5b32a39c3e904a94af8c0ef4f8963b3-1729414573.ap-south-1.elb.amazonaws.com:444"
            - name: CRATER_DB_HOST
              value: "craterdb"
            - name: CRATER_DB_PORT
              value: "3306"
            - name: CRATER_DB_DATABASE
              value: "crater"
            - name: CRATER_DB_USERNAME
              value: "crater"
            - name: CRATER_DB_PASSWORD
              value: "crater"
            - name: CRATER_SANCTUM_STATEFUL_DOMAINS
              value: "a5b32a39c3e904a94af8c0ef4f8963b3-1729414573.ap-south-1.elb.amazonaws.com:444"
            - name: CRATER_SESSION_DOMAIN
              value: "a5b32a39c3e904a94af8c0ef4f8963b3-1729414573.ap-south-1.elb.amazonaws.com"
            - name: CRATER_AUTO_INSTALL
              value: "true"
            - name: CRATER_ADMIN_NAME
              value: "Super Man"
            - name: CRATER_ADMIN_EMAIL
              value: "superman@bahmni.org"
            - name: CRATER_ADMIN_PASSWORD
              value: "Crater123"
            - name: CRATER_COMPANY_NAME
              value: "Bahmni"
            - name: CRATER_COMPANY_SLUG
              value: "Bahmni"
            - name: CRATER_COUNTRY_ID
              value: "101"
            - name: CRATER_APP_DEBUG
              value: "false"
            - name: CRATER_DEFAULT_CURRENCY
              value: "USD"



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: crater-php
#   name: crater-php
#   namespace: default
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: crater-php
#   template:
#     metadata:
#       labels:
#         app: crater-php
#     spec:
#       containers:
#       - image: 779846789022.dkr.ecr.ap-south-1.amazonaws.com/crater-php:1.0.0
#         name: crater-php
#         ports:
#         - containerPort: 9000
#         env:
#         - name: CRATER_APP_URL
#           value: "https://payments-aa51414fb77674c63b202ced9aef1cfd-1457186657.ap-south-1.elb.amazonaws.com"
#         - name: CRATER_DB_HOST
#           value: "craterdb"
#         - name: CRATER_DB_PORT
#           value: "3306"
#         - name: CRATER_DB_DATABASE
#           value: "crater"
#         - name: CRATER_DB_USERNAME
#           value: "crater"
#         - name: CRATER_DB_PASSWORD
#           value: "crater"
#         - name: CRATER_SANCTUM_STATEFUL_DOMAINS
#           value: "payments-aa51414fb77674c63b202ced9aef1cfd-1457186657.ap-south-1.elb.amazonaws.com"
#         - name: CRATER_SESSION_DOMAIN
#           value: "payments-aa51414fb77674c63b202ced9aef1cfd-1457186657.ap-south-1.elb.amazonaws.com"
#         - name: CRATER_AUTO_INSTALL
#           value: "true"
#         - name: CRATER_ADMIN_NAME
#           value: "Super Man"
#         - name: CRATER_ADMIN_EMAIL
#           value: "superman@bahmni.org"
#         - name: CRATER_ADMIN_PASSWORD
#           value: "Crater123"
#         - name: CRATER_COMPANY_NAME
#           value: "Bahmni"
#         - name: CRATER_COMPANY_SLUG
#           value: "Bahmni"
#         - name: CRATER_COUNTRY_ID
#           value: "101"
#         - name: CRATER_APP_DEBUG
#           value: "false"