apiVersion: v1
kind: Service
metadata:
  name: crater-php
spec:
  selector:
    app: crater-php
  ports:
    - protocol: TCP
      port: 9000           # Public/external port
      targetPort: 9000    # Container's internal port
  type: LoadBalancer

