apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-documents
  labels:
    app: patient-documents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-documents
  template:
    metadata:
      labels:
        app: patient-documents
    spec:
      containers:
        - name: patient-documents
          image: 779846789022.dkr.ecr.ap-south-1.amazonaws.com/patient-documents:1.0.0
          ports:
            - containerPort: 80
          env:
            - name: OPENMRS_HOST
              value: "openmrs"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: regcred