apiVersion: v1
kind: Service
metadata:
  name: crater-atomfeed-db
  labels:
    app: crater-atomfeed-db
spec:
  selector:
    app: crater-atomfeed-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
