# Persistent Volume for Bahmni Configuration
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bahmni-config-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/bahmni-config