apiVersion: apps/v1
kind: Deployment
metadata:
  name: crater-php
  labels:
    app: crater-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crater-php
  template:
    metadata:
      labels:
        app: crater-php
    spec:
      containers:
        - name: crater-php
          image: 779846789022.dkr.ecr.ap-south-1.amazonaws.com/crater-php:1.0.0
          ports:
            - containerPort: 9000
      imagePullSecrets:
        - name: regcred
