# Persistent Volume Claim for Bahmni Configuration
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bahmni-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
